services:
  eureka:
    build: eureka-server
    ports:
      - 8761:8761
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka
  gateway:
    build: gateway
    ports:
      - 8080:8080
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  service1:
    build: service1
    ports:
      - 8111:8111
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  service2:
    build: service2
    ports:
      - 8222:8222
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
