### list registered services
### Open http://localhost:8761/ in browser
GET http://localhost:8761/eureka/apps

### call SERVICE 1
GET http://localhost:8111/greetings

### call SERVICE 2
GET http://localhost:8222/info

### call SERVICE 1 via gateway
GET http://localhost:8080/service1/greetings
