server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-server
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://SERVICE1
          predicates:
            - Path=/service1/**
          filters:
            - RewritePath=/service1/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
